AWSTemplateFormatVersion: '2010-09-09'
Description: Applicate Managed Microsoft AD and Workspaces
#CloudFormation: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-directoryservice-microsoftad.html#cfn-directoryservice-microsoftad-vpcsettings
#AD API reference: https://docs.aws.amazon.com/ja_jp/directoryservice/latest/devguide/welcome.html
#------------------
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
  ADname:
    Type: String   
  ADPassword:
    Type: String
    MinLength: 8
    MaxLength: 64
    NoEcho: true
#------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "General"
        Parameters:
          - Environment
      -
        Label:
          default: "Microsoft AD"
        Parameters:
          - ADname
          - ADPassword
#----------------------------------------------
Resources:
  AD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: !Ref ADname
      CreateAlias: true
      Edition: Standard
      Password: !Ref ADPassword
      VpcSettings:
        VpcId:
          Fn::ImportValue: !Sub ${Environment}-OperationVPC-VpcId
        SubnetIds:
          - Fn::ImportValue: !Sub ${Environment}-OperationVPC-Subnet1Id
          - Fn::ImportValue: !Sub ${Environment}-OperationVPC-Subnet2Id
Outputs:
  ADId:
    Description: Active Drectory ID
    Value: !Ref AD
    Export:
      Name: !Sub "${AWS::StackName}-ADId"