AWSTemplateFormatVersion: '2010-09-09'
Description: Applicate VPC peering which connects to CommonVPC and OperationVPC
#------------------
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
#------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "General"
        Parameters:
          - Environment
#----------------------------------------------
Resources:
  #------------------ VPC Peering
  VpcPeering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-CommonVPC-VpcId
      PeerVpcId: 
        Fn::ImportValue: !Sub ${Environment}-OperationVPC-VpcId
      Tags:
        - Key: Name
          Value: VPCPeer-CommnVPCandOperationVPC
  #------------------ Add routings
  #--- CommonVpc
  AddRouteCommonVpcToOperationVpcRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-CommonVPC-RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-OperationVPC-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  AddRouteOperationVpcToCommonVpcRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-OperationVPC-RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-CommonVPC-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  AddRouteOperationVpcToCommonVpcPublicRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-OperationVPC-PublicRouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-CommonVPC-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering