AWSTemplateFormatVersion: '2010-09-09'
Description: VPN
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
  #------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      -
        Label:
          default: "General Configurations"
        Parameters:
          - Environment
#----------------------------------------------
Resources:
  #------------------ CustomerGW
  CustomerGW:
    Type: AWS::EC2::CustomerGateway
    Properties:
      Type: ipsec.1
      BgpAsn: 65000
      IpAddress:
        Fn::ImportValue: !Sub ${Environment}-ClientVPC-CustomerGWPublicIP
      Tags:
        - Key: Name
          Value: CustomerGWofClientVPC
  #------------------ Transit Gateway
  TgwVpn:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      Description: "TransitGateway to VPN"
      #AmazonSideAsn: Integer
      #AutoAcceptSharedAttachments: String
      DefaultRouteTableAssociation: "disable"
      DefaultRouteTablePropagation: "disable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        - Key: "Name"
          Value: "VPN-TGW"
  AttachTgwToVpc:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      TransitGatewayId: !Ref TgwVpn
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-OutboundVPC-VpcId
      SubnetIds: 
        - Fn::ImportValue: !Sub ${Environment}-OutboundVPC-PrivateSubnet1Id
        - Fn::ImportValue: !Sub ${Environment}-OutboundVPC-PrivateSubnet2Id
  #---TGW Route Table
  TgwRouteTable:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      TransitGatewayId: !Ref TgwVpn
      Tags: 
        - Key: "Name"
          Value: "VPN-TGW-RouteTable"
  TgwRouteTableAttacheToVPCAssociation:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    Properties:
      TransitGatewayAttachmentId: !Ref AttachTgwToVpc
      TransitGatewayRouteTableId: !Ref TgwRouteTable
  TgwRouteTableAttacheToVPCPropagation:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref AttachTgwToVpc
      TransitGatewayRouteTableId: !Ref TgwRouteTable
  #---TGW: Add DefaultGW
  AddRouteDefaultGw:
    Type: "AWS::EC2::TransitGatewayRoute"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      TransitGatewayAttachmentId: !Ref AttachTgwToVpc
      TransitGatewayRouteTableId: !Ref TgwRouteTable

#  #------------------ Virtual private GW
# Deploy by cli, because attaching tgw to vpn is unsupported cloudformation.
#  VpnGW:
#    Type: AWS::EC2::VPNGateway
#    Properties: 
#      Type: ipsec.1
#      Tags:
#        - Key: Name
#          Value: VPNGatewayforOutboundVPC
#  VpnConnection:
#    Type: AWS::EC2::VPNConnection
#    Properties: 
#      Type: ipsec.1
#      CustomerGatewayId: !Ref CustomerGW
#      VpnGatewayId: !Ref VpnGW
#------------------ 
Outputs:
  CustomerGWId:
    Description:  Customer Gateway ID
    Value: !Ref CustomerGW
    Export:
      Name: !Sub "${AWS::StackName}-CustomerGWId"
  TgwVpnId:
    Description:  TransitGateway for VPN ID
    Value: !Ref TgwVpn
    Export:
      Name: !Sub "${AWS::StackName}-TgwVpnId"
  AttachTgwToVpcId:
    Description: Attachement ID of Outbound VPC
    Value: !Ref AttachTgwToVpc
    Export:
      Name: !Sub "${AWS::StackName}-AttachTgwToVpcId"
  TgwRouteTableId:
    Description:  TransitGatewayTable ID
    Value: !Ref TgwRouteTable
    Export:
      Name: !Sub "${AWS::StackName}-TgwRouteTableId"

