AWSTemplateFormatVersion: '2010-09-09'
Description: VPN
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
  #------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      -
        Label:
          default: "General Configurations"
        Parameters:
          - Environment
#----------------------------------------------
Resources:
  #------------------ CustomerGW
  CustomerGW:
    Type: AWS::EC2::CustomerGateway
    Properties:
      Type: ipsec.1
      BgpAsn: 65000
      IpAddress:
        Fn::ImportValue: !Sub ${Environment}-ClientVPC-CustomerGW1PublicIP
      Tags:
        - Key: Name
          Value: CustomerGW1ofClientVPC
  #------------------ Virtual private GW
  VpnGW:
    Type: AWS::EC2::VPNGateway
    Properties: 
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: VPNGatewayforOutboundVPC
  AttachVgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpnGatewayId: !Ref VpnGW
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-OutboundVPC-VpcId
    DependsOn:
      - VpnGW
  VpnConnection:
    Type: AWS::EC2::VPNConnection
    Properties: 
      Type: ipsec.1
      CustomerGatewayId: !Ref CustomerGW
      VpnGatewayId: !Ref VpnGW
  #------------------ Add route to OutboundVPC table
  AddVpnGWToVpnRouteTable1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-OutboundVPC-VpnSubnet1RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-ClientVPC-VpcCidr
      GatewayId: !Ref VpnGW
    DependsOn:
      - AttachVgw
  AddVpnGWToPVpnRouteTable2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-OutboundVPC-VpnSubnet2RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-ClientVPC-VpcCidr
      GatewayId: !Ref VpnGW
    DependsOn:
      - AttachVgw